### ISSUE TITLE
Problem when reproducing from torrent

### ISSUE THREAD

**Issue by alesnav** [tarasian666/acestream#3]
I have a problem trying to reproducing a torrent file. I will use AceStream test torrent file from `info.acestream.org`

```
2014-03-07 19:29:13 bg::loading TORRENT http://info.acestream.org/dl/5953213c22c304b4f2aab0029a0915fbadca3f8a.torrent
2014-03-07 19:29:14 bg::get_torrent_start_download: dlfile: sintel-1024-surround.mp4  fileindex: 0
2014-03-07 19:29:14 bg: get_torrent_start_download: Starting new Download
2014-03-07 19:29:14 {'BaseApp::start_download: starting new download: infohash T\x10\xb2\x7f\xc5g\xc3\\\x85G\xe3\xb6\x9b\x14\x12\x15\xce:\x1f\xd7 initialdlstatus None'}
2014-03-07 19:29:17 STATE 2
2014-03-07 19:29:18 bg::loading TORRENT http://info.acestream.org/dl/5953213c22c304b4f2aab0029a0915fbadca3f8a.torrent
2014-03-07 19:29:18 bg::get_torrent_start_download: dlfile: sintel-1024-surround.mp4  fileindex: 0
2014-03-07 19:29:19 {'BaseApp::start_download: Reusing old duplicate download T\x10\xb2\x7f\xc5g\xc3\\\x85G\xe3\xb6\x9b\x14\x12\x15\xce:\x1f\xd7'}
Traceback (most recent call last):
  File "/etc/p2ptv-pi/acestream/ACEStream/Core/BitTornado/BT1/GetRightHTTPDownloader.py", line 235, in _start_proxy
    resched = self.read_raw(pos, speed)
  File "/etc/p2ptv-pi/acestream/ACEStream/Core/BitTornado/BT1/GetRightHTTPDownloader.py", line 426, in read_raw
    seek_pos = self.downloader.voddownload.got_proxy_data(pos, chunk)
  File "/etc/p2ptv-pi/acestream/ACEStream/Core/Video/VideoOnDemand.py", line 1427, in got_proxy_data
    elif self.proxy_buf.has_key(pos):
AttributeError: MovieOnDemandTransporter instance has no attribute 'proxy_buf'

2014-03-07 19:29:19 STATE 2
Traceback (most recent call last):
  File "/etc/p2ptv-pi/acestream/ACEStream/Video/VideoServer.py", line 402, in do_GET
    self.server.release_inputstream(self.server.url_is_set)
  File "/etc/p2ptv-pi/acestream/ACEStream/Video/VideoServer.py", line 145, in release_inputstream
    streaminfo['lock'].release()
  File "/usr/lib/python2.7/threading.py", line 143, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock

2014-03-07 19:29:202014-03-07 19:29:20 bg: Video server reported error cannot release un-acquired lock
 bg::loading TORRENT http://info.acestream.org/dl/5953213c22c304b4f2aab0029a0915fbadca3f8a.torrent
2014-03-07 19:29:20 ic::got command stop
2014-03-07 19:29:20 bg::cleanup_playback
2014-03-07 19:29:20 bg: Shutting down: shutdownplugin True
2014-03-07 19:29:20 bg::cleanup_playback
2014-03-07 19:29:20 bg::get_torrent_start_download: dlfile: sintel-1024-surround.mp4  fileindex: 0
2014-03-07 19:29:20 {'BaseApp::start_download: Reusing old duplicate download T\x10\xb2\x7f\xc5g\xc3\\\x85G\xe3\xb6\x9b\x14\x12\x15\xce:\x1f\xd7'}
2014-03-07 19:29:20 STATE 2
Traceback (most recent call last):
  File "/etc/p2ptv-pi/acestream/ACEStream/Video/VideoServer.py", line 270, in do_GET
    self.send_response(416)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
    self.send_header('Date', self.date_time_string())
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
  File "/usr/lib/python2.7/socket.py", line 324, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe

2014-03-07 19:29:21 ic::got command stop
2014-03-07 19:29:21 bg::cleanup_playback
2014-03-07 19:29:21 bg: Shutting down: shutdownplugin True
2014-03-07 19:29:22 bg::remove_playing_download: hash 5410b27fc567c35c8547e3b69b141215ce3a1fd7
2014-03-07 19:29:22 bg::remove_playing_download: yes, no interest: removecontent False stop True
```

Can you please help me?

Thanks!

P.D.: may I write a README file for your project? :)

**Comment by tarasian666** [comment]
This bug i can't fix, sorry. In other player it may be not approved.

P.S: yes)

**Comment by alesnav** [comment]
So, is ".acelive" the only filetype available for playing using http://127.0.0.1:6878/LOAD/TORRENT=http://url.to/channel.acestream ?

**Comment by tarasian666** [comment]
Yes(not fully tested), but via api - works all.
